language: node_js
node_js:
  - 12
jobs:
  include: 
    - stage: Unit Tests
      install:
        - travis_retry npm install
      script: 
        - npm run test
    - stage: Dry Release
      script:
        - npm run release:dry
    - stage: Release
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run release:dry
        on:
          branch: master