version: ~> 1.0
language: node_js
node_js:
  - 12
jobs:
  include: 
    - stage: Unit Tests
    install:
      - travis_retry npm install
    script: 
      - npm run test
    - stage: Dry Release
    script:
      - npm run release:dry